Changes made to react router and header
Lambda-School-Labs/PT17_cityspire-f-fe pull request #8
Opened 2021-03-27 02:23 UTC by JoelGonzalez02

-Updated files to pass tests
-Changed react router for home page

Joel Gonzalez

2021-03-28 02:14 UTC, tinomen requested changes

2021-03-28 02:14 UTC, tinomen commented on src/components/pages/Home/HomeContainer.js
> +      {/* {!authState.isAuthenticated && !userInfo && <RenderHomePage />} */}
lets not get commented out code into our main branch. Delete the code if it is no longer needed/wanted.

2021-03-28 02:14 UTC, tinomen commented on src/components/common/Header.js
> +            {/* <Button onClick={() => authService.logout()}>Logout</Button> */}
Remove commented out code.

2021-03-28 02:14 UTC, tinomen commented on src/components/App.js
> +        {/* Removed the SecurerRoute component so that the HomePage loads first -JG */}
What is the driver for this? Couldn't we introduce a new Landing page to be the root path?

2021-03-28 02:20 UTC, tinomen commented
The description doesn't provide much in the way of motivation for the change to the home page. Also, the changes made to pass test is very unclear. Is that the motivation to change the homepage? If not, lets separate the 2 issues into different PRs.

2021-03-29 04:08 UTC, sarahmarie1976 commented
See Jakes Comments and update what he suggested.

2021-03-29 04:15 UTC, sarahmarie1976 requested changes
Look at Jakes comments. He wants you to be more detailed about what you did on your pull request. And for future PR he wants small individual PR. Once you update what Jake suggest and you push up again I will approve it. :-)

2021-03-30 02:59 UTC, sarahmarie1976 commented
Thanks for updating the routes to show the landing page. And awesome job on passing all the tests from jest

2021-03-30 02:59 UTC, closed without merging

2021-03-30 03:00 UTC, sarahmarie1976 approved these changes